import CONSTANTES from '../../../../constantes';


let getProfesorOptions = (type) => {

    switch (type) {
        case CONSTANTES.MODALIDAD_SELECT_OPTIONS.GENERAL:
            return CONSTANTES.PROFESOR_GENERAL_OPTIONS;

        case CONSTANTES.MODALIDAD_SELECT_OPTIONS.TECNICO_CONTA:
            return CONSTANTES.PROFESOR_TECNICO_CONTA_OPTIONS;

        case CONSTANTES.MODALIDAD_SELECT_OPTIONS.TECNICO_ELECTR:
            return CONSTANTES.PROFESOR_TECNICO_ELECTR_OPTIONS;
        
        case CONSTANTES.MODALIDAD_SELECT_OPTIONS.TECNICO_INF:
            
            return CONSTANTES.PROFESOR_TECNICO_ELECTR_OPTIONS;
        
        case CONSTANTES.MODALIDAD_SELECT_OPTIONS.TECNICO_MER:
            
            return CONSTANTES.PROFESOR_TECNICO_MER_OPTIONS;

        case CONSTANTES.MODALIDAD_SELECT_OPTIONS.TECNICO_TURIS:
            
            return CONSTANTES.PROFESOR_TECNICO_TURIS_OPTIONS;

        default:
            return CONSTANTES.PROFESOR_GENERAL_OPTIONS;
    }

}

let getAsignaturaOptions = (type) =>{

    switch (type) {
        case CONSTANTES.MODALIDAD_SELECT_OPTIONS.GENERAL:
            return CONSTANTES.ASIGNATURA_GENERAL_OPTIONS;

        case CONSTANTES.MODALIDAD_SELECT_OPTIONS.TECNICO_CONTA:
            return CONSTANTES.ASIGNATURA_TECNICO_CONTA_OPTIONS;

        case CONSTANTES.MODALIDAD_SELECT_OPTIONS.TECNICO_ELECTR:
            return CONSTANTES.ASIGNATURA_TECNICO_ELECTR_OPTIONS;
        
        case CONSTANTES.MODALIDAD_SELECT_OPTIONS.TECNICO_INF:
            
            return CONSTANTES.ASIGNATURA_TECNICO_INF_OPTIONS;
        
        case CONSTANTES.MODALIDAD_SELECT_OPTIONS.TECNICO_MER:
            
            return CONSTANTES.ASIGNATURA_TECNICO_MER_OPTIONS;

        case CONSTANTES.MODALIDAD_SELECT_OPTIONS.TECNICO_TURIS:
            
            return CONSTANTES.ASIGNATURA_TECNICO_TURIS_OPTIONS;

        default:
            return CONSTANTES.ASIGNATURA_GENERAL_OPTIONS;
    }

}


export {
    getAsignaturaOptions,
    getProfesorOptions
}